#ifndef __SNIFFER_CONFIG_H
#define __SNIFFER_CONFIG_H

// config for Nordic PCA10056 Dev Kit using SEGGER J-Link OB for communication

// NRF_UART_BAUDRATE_115200
// NRF_UART_BAUDRATE_230400
// NRF_UART_BAUDRATE_460800
// NRF_UART_BAUDRATE_921600
// NRF_UART_BAUDRATE_1000000
#define SNIFFER_UART_BAUDRATE     NRF_UART_BAUDRATE_1000000

// NRF_UART_HWFC_DISABLED
// NRF_UART_HWFC_ENABLED
#define SNIFFER_UART_FLOWCONTROL  NRF_UART_HWFC_ENABLED

#endif
